services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
  cerbot:
    restart: always
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email
      cccchenyuhao@gmail.com --agree-tos --no-eff-email --staging -d icyh.me
